#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_0_Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CENTRO_IDIOMAS")]
	public partial class DB_CentroIdiomasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLASES(CLASES instance);
    partial void UpdateCLASES(CLASES instance);
    partial void DeleteCLASES(CLASES instance);
    partial void InsertPROGRAMA(PROGRAMA instance);
    partial void UpdatePROGRAMA(PROGRAMA instance);
    partial void DeletePROGRAMA(PROGRAMA instance);
    partial void InsertCURSOS(CURSOS instance);
    partial void UpdateCURSOS(CURSOS instance);
    partial void DeleteCURSOS(CURSOS instance);
    partial void InsertCURSOS_ESTUDIANTE(CURSOS_ESTUDIANTE instance);
    partial void UpdateCURSOS_ESTUDIANTE(CURSOS_ESTUDIANTE instance);
    partial void DeleteCURSOS_ESTUDIANTE(CURSOS_ESTUDIANTE instance);
    partial void InsertESTUDIANTES(ESTUDIANTES instance);
    partial void UpdateESTUDIANTES(ESTUDIANTES instance);
    partial void DeleteESTUDIANTES(ESTUDIANTES instance);
    partial void InsertFERIADOS(FERIADOS instance);
    partial void UpdateFERIADOS(FERIADOS instance);
    partial void DeleteFERIADOS(FERIADOS instance);
    partial void InsertLOGINS(LOGINS instance);
    partial void UpdateLOGINS(LOGINS instance);
    partial void DeleteLOGINS(LOGINS instance);
    partial void InsertMATRICULA(MATRICULA instance);
    partial void UpdateMATRICULA(MATRICULA instance);
    partial void DeleteMATRICULA(MATRICULA instance);
    partial void InsertPROFESORES(PROFESORES instance);
    partial void UpdatePROFESORES(PROFESORES instance);
    partial void DeletePROFESORES(PROFESORES instance);
    #endregion
		
		public DB_CentroIdiomasDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CENTRO_IDIOMASConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CentroIdiomasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CentroIdiomasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CentroIdiomasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_CentroIdiomasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLASES> CLASES
		{
			get
			{
				return this.GetTable<CLASES>();
			}
		}
		
		public System.Data.Linq.Table<PROGRAMA> PROGRAMA
		{
			get
			{
				return this.GetTable<PROGRAMA>();
			}
		}
		
		public System.Data.Linq.Table<CURSOS> CURSOS
		{
			get
			{
				return this.GetTable<CURSOS>();
			}
		}
		
		public System.Data.Linq.Table<CURSOS_ESTUDIANTE> CURSOS_ESTUDIANTE
		{
			get
			{
				return this.GetTable<CURSOS_ESTUDIANTE>();
			}
		}
		
		public System.Data.Linq.Table<ESTUDIANTES> ESTUDIANTES
		{
			get
			{
				return this.GetTable<ESTUDIANTES>();
			}
		}
		
		public System.Data.Linq.Table<FERIADOS> FERIADOS
		{
			get
			{
				return this.GetTable<FERIADOS>();
			}
		}
		
		public System.Data.Linq.Table<LOGINS> LOGINS
		{
			get
			{
				return this.GetTable<LOGINS>();
			}
		}
		
		public System.Data.Linq.Table<MATRICULA> MATRICULA
		{
			get
			{
				return this.GetTable<MATRICULA>();
			}
		}
		
		public System.Data.Linq.Table<PROFESORES> PROFESORES
		{
			get
			{
				return this.GetTable<PROFESORES>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CURSO_IDIOMA")]
		public int CURSO_IDIOMA([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_curso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] ref string idioma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_curso, idioma);
			idioma = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CURSO_NEXT")]
		public int CURSO_NEXT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_estudiante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string idioma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] ref string msj)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_estudiante, idioma, msj);
			msj = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLASES")]
	public partial class CLASES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CLASE;
		
		private int _ID_ESTUDIANTE;
		
		private int _ID_PROFESOR;
		
		private int _ID_CURSO;
		
		private System.DateTime _INICIO;
		
		private System.DateTime _FINAL;
		
		private bool _BORRADO_E;
		
		private EntityRef<CURSOS> _CURSOS;
		
		private EntityRef<ESTUDIANTES> _ESTUDIANTES;
		
		private EntityRef<PROFESORES> _PROFESORES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CLASEChanging(int value);
    partial void OnID_CLASEChanged();
    partial void OnID_ESTUDIANTEChanging(int value);
    partial void OnID_ESTUDIANTEChanged();
    partial void OnID_PROFESORChanging(int value);
    partial void OnID_PROFESORChanged();
    partial void OnID_CURSOChanging(int value);
    partial void OnID_CURSOChanged();
    partial void OnINICIOChanging(System.DateTime value);
    partial void OnINICIOChanged();
    partial void OnFINALChanging(System.DateTime value);
    partial void OnFINALChanged();
    partial void OnBORRADO_EChanging(bool value);
    partial void OnBORRADO_EChanged();
    #endregion
		
		public CLASES()
		{
			this._CURSOS = default(EntityRef<CURSOS>);
			this._ESTUDIANTES = default(EntityRef<ESTUDIANTES>);
			this._PROFESORES = default(EntityRef<PROFESORES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CLASE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CLASE
		{
			get
			{
				return this._ID_CLASE;
			}
			set
			{
				if ((this._ID_CLASE != value))
				{
					this.OnID_CLASEChanging(value);
					this.SendPropertyChanging();
					this._ID_CLASE = value;
					this.SendPropertyChanged("ID_CLASE");
					this.OnID_CLASEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTUDIANTE", DbType="Int NOT NULL")]
		public int ID_ESTUDIANTE
		{
			get
			{
				return this._ID_ESTUDIANTE;
			}
			set
			{
				if ((this._ID_ESTUDIANTE != value))
				{
					if (this._ESTUDIANTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ESTUDIANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_ESTUDIANTE = value;
					this.SendPropertyChanged("ID_ESTUDIANTE");
					this.OnID_ESTUDIANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFESOR", DbType="Int NOT NULL")]
		public int ID_PROFESOR
		{
			get
			{
				return this._ID_PROFESOR;
			}
			set
			{
				if ((this._ID_PROFESOR != value))
				{
					if (this._PROFESORES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PROFESORChanging(value);
					this.SendPropertyChanging();
					this._ID_PROFESOR = value;
					this.SendPropertyChanged("ID_PROFESOR");
					this.OnID_PROFESORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CURSO", DbType="Int NOT NULL")]
		public int ID_CURSO
		{
			get
			{
				return this._ID_CURSO;
			}
			set
			{
				if ((this._ID_CURSO != value))
				{
					if (this._CURSOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CURSOChanging(value);
					this.SendPropertyChanging();
					this._ID_CURSO = value;
					this.SendPropertyChanged("ID_CURSO");
					this.OnID_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INICIO", DbType="DateTime NOT NULL")]
		public System.DateTime INICIO
		{
			get
			{
				return this._INICIO;
			}
			set
			{
				if ((this._INICIO != value))
				{
					this.OnINICIOChanging(value);
					this.SendPropertyChanging();
					this._INICIO = value;
					this.SendPropertyChanged("INICIO");
					this.OnINICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINAL", DbType="DateTime NOT NULL")]
		public System.DateTime FINAL
		{
			get
			{
				return this._FINAL;
			}
			set
			{
				if ((this._FINAL != value))
				{
					this.OnFINALChanging(value);
					this.SendPropertyChanging();
					this._FINAL = value;
					this.SendPropertyChanged("FINAL");
					this.OnFINALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORRADO_E", DbType="Bit NOT NULL")]
		public bool BORRADO_E
		{
			get
			{
				return this._BORRADO_E;
			}
			set
			{
				if ((this._BORRADO_E != value))
				{
					this.OnBORRADO_EChanging(value);
					this.SendPropertyChanging();
					this._BORRADO_E = value;
					this.SendPropertyChanged("BORRADO_E");
					this.OnBORRADO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_CLASES", Storage="_CURSOS", ThisKey="ID_CURSO", OtherKey="ID_CURSO", IsForeignKey=true)]
		public CURSOS CURSOS
		{
			get
			{
				return this._CURSOS.Entity;
			}
			set
			{
				CURSOS previousValue = this._CURSOS.Entity;
				if (((previousValue != value) 
							|| (this._CURSOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CURSOS.Entity = null;
						previousValue.CLASES.Remove(this);
					}
					this._CURSOS.Entity = value;
					if ((value != null))
					{
						value.CLASES.Add(this);
						this._ID_CURSO = value.ID_CURSO;
					}
					else
					{
						this._ID_CURSO = default(int);
					}
					this.SendPropertyChanged("CURSOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_CLASES", Storage="_ESTUDIANTES", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE", IsForeignKey=true)]
		public ESTUDIANTES ESTUDIANTES
		{
			get
			{
				return this._ESTUDIANTES.Entity;
			}
			set
			{
				ESTUDIANTES previousValue = this._ESTUDIANTES.Entity;
				if (((previousValue != value) 
							|| (this._ESTUDIANTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ESTUDIANTES.Entity = null;
						previousValue.CLASES.Remove(this);
					}
					this._ESTUDIANTES.Entity = value;
					if ((value != null))
					{
						value.CLASES.Add(this);
						this._ID_ESTUDIANTE = value.ID_ESTUDIANTE;
					}
					else
					{
						this._ID_ESTUDIANTE = default(int);
					}
					this.SendPropertyChanged("ESTUDIANTES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_CLASES", Storage="_PROFESORES", ThisKey="ID_PROFESOR", OtherKey="ID_PROFESOR", IsForeignKey=true)]
		public PROFESORES PROFESORES
		{
			get
			{
				return this._PROFESORES.Entity;
			}
			set
			{
				PROFESORES previousValue = this._PROFESORES.Entity;
				if (((previousValue != value) 
							|| (this._PROFESORES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROFESORES.Entity = null;
						previousValue.CLASES.Remove(this);
					}
					this._PROFESORES.Entity = value;
					if ((value != null))
					{
						value.CLASES.Add(this);
						this._ID_PROFESOR = value.ID_PROFESOR;
					}
					else
					{
						this._ID_PROFESOR = default(int);
					}
					this.SendPropertyChanged("PROFESORES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROGRAMA")]
	public partial class PROGRAMA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PROGRAMA;
		
		private string _IDIOMA;
		
		private int _CURSOS;
		
		private bool _BORRADO_E;
		
		private EntitySet<CURSOS> _CURSOS1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PROGRAMAChanging(int value);
    partial void OnID_PROGRAMAChanged();
    partial void OnIDIOMAChanging(string value);
    partial void OnIDIOMAChanged();
    partial void OnCURSOSChanging(int value);
    partial void OnCURSOSChanged();
    partial void OnBORRADO_EChanging(bool value);
    partial void OnBORRADO_EChanged();
    #endregion
		
		public PROGRAMA()
		{
			this._CURSOS1 = new EntitySet<CURSOS>(new Action<CURSOS>(this.attach_CURSOS1), new Action<CURSOS>(this.detach_CURSOS1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROGRAMA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PROGRAMA
		{
			get
			{
				return this._ID_PROGRAMA;
			}
			set
			{
				if ((this._ID_PROGRAMA != value))
				{
					this.OnID_PROGRAMAChanging(value);
					this.SendPropertyChanging();
					this._ID_PROGRAMA = value;
					this.SendPropertyChanged("ID_PROGRAMA");
					this.OnID_PROGRAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDIOMA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IDIOMA
		{
			get
			{
				return this._IDIOMA;
			}
			set
			{
				if ((this._IDIOMA != value))
				{
					this.OnIDIOMAChanging(value);
					this.SendPropertyChanging();
					this._IDIOMA = value;
					this.SendPropertyChanged("IDIOMA");
					this.OnIDIOMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURSOS", DbType="Int NOT NULL")]
		public int CURSOS
		{
			get
			{
				return this._CURSOS;
			}
			set
			{
				if ((this._CURSOS != value))
				{
					this.OnCURSOSChanging(value);
					this.SendPropertyChanging();
					this._CURSOS = value;
					this.SendPropertyChanged("CURSOS");
					this.OnCURSOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORRADO_E", DbType="Bit NOT NULL")]
		public bool BORRADO_E
		{
			get
			{
				return this._BORRADO_E;
			}
			set
			{
				if ((this._BORRADO_E != value))
				{
					this.OnBORRADO_EChanging(value);
					this.SendPropertyChanging();
					this._BORRADO_E = value;
					this.SendPropertyChanged("BORRADO_E");
					this.OnBORRADO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROGRAMA_CURSOS", Storage="_CURSOS1", ThisKey="ID_PROGRAMA", OtherKey="ID_PROGRAMA")]
		public EntitySet<CURSOS> CURSOS1
		{
			get
			{
				return this._CURSOS1;
			}
			set
			{
				this._CURSOS1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOS1(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.PROGRAMA = this;
		}
		
		private void detach_CURSOS1(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.PROGRAMA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CURSOS")]
	public partial class CURSOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CURSO;
		
		private int _ID_PROGRAMA;
		
		private string _NOMBRE_CURSO;
		
		private string _REQUISITO;
		
		private int _HORAS;
		
		private decimal _COSTO;
		
		private bool _BORRADO_E;
		
		private EntitySet<CLASES> _CLASES;
		
		private EntitySet<CURSOS_ESTUDIANTE> _CURSOS_ESTUDIANTE;
		
		private EntitySet<MATRICULA> _MATRICULA;
		
		private EntityRef<PROGRAMA> _PROGRAMA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CURSOChanging(int value);
    partial void OnID_CURSOChanged();
    partial void OnID_PROGRAMAChanging(int value);
    partial void OnID_PROGRAMAChanged();
    partial void OnNOMBRE_CURSOChanging(string value);
    partial void OnNOMBRE_CURSOChanged();
    partial void OnREQUISITOChanging(string value);
    partial void OnREQUISITOChanged();
    partial void OnHORASChanging(int value);
    partial void OnHORASChanged();
    partial void OnCOSTOChanging(decimal value);
    partial void OnCOSTOChanged();
    partial void OnBORRADO_EChanging(bool value);
    partial void OnBORRADO_EChanged();
    #endregion
		
		public CURSOS()
		{
			this._CLASES = new EntitySet<CLASES>(new Action<CLASES>(this.attach_CLASES), new Action<CLASES>(this.detach_CLASES));
			this._CURSOS_ESTUDIANTE = new EntitySet<CURSOS_ESTUDIANTE>(new Action<CURSOS_ESTUDIANTE>(this.attach_CURSOS_ESTUDIANTE), new Action<CURSOS_ESTUDIANTE>(this.detach_CURSOS_ESTUDIANTE));
			this._MATRICULA = new EntitySet<MATRICULA>(new Action<MATRICULA>(this.attach_MATRICULA), new Action<MATRICULA>(this.detach_MATRICULA));
			this._PROGRAMA = default(EntityRef<PROGRAMA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CURSO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CURSO
		{
			get
			{
				return this._ID_CURSO;
			}
			set
			{
				if ((this._ID_CURSO != value))
				{
					this.OnID_CURSOChanging(value);
					this.SendPropertyChanging();
					this._ID_CURSO = value;
					this.SendPropertyChanged("ID_CURSO");
					this.OnID_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROGRAMA", DbType="Int NOT NULL")]
		public int ID_PROGRAMA
		{
			get
			{
				return this._ID_PROGRAMA;
			}
			set
			{
				if ((this._ID_PROGRAMA != value))
				{
					if (this._PROGRAMA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PROGRAMAChanging(value);
					this.SendPropertyChanging();
					this._ID_PROGRAMA = value;
					this.SendPropertyChanged("ID_PROGRAMA");
					this.OnID_PROGRAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CURSO", DbType="VarChar(50)")]
		public string NOMBRE_CURSO
		{
			get
			{
				return this._NOMBRE_CURSO;
			}
			set
			{
				if ((this._NOMBRE_CURSO != value))
				{
					this.OnNOMBRE_CURSOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_CURSO = value;
					this.SendPropertyChanged("NOMBRE_CURSO");
					this.OnNOMBRE_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REQUISITO", DbType="VarChar(50)")]
		public string REQUISITO
		{
			get
			{
				return this._REQUISITO;
			}
			set
			{
				if ((this._REQUISITO != value))
				{
					this.OnREQUISITOChanging(value);
					this.SendPropertyChanging();
					this._REQUISITO = value;
					this.SendPropertyChanged("REQUISITO");
					this.OnREQUISITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAS", DbType="Int NOT NULL")]
		public int HORAS
		{
			get
			{
				return this._HORAS;
			}
			set
			{
				if ((this._HORAS != value))
				{
					this.OnHORASChanging(value);
					this.SendPropertyChanging();
					this._HORAS = value;
					this.SendPropertyChanged("HORAS");
					this.OnHORASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTO", DbType="Decimal(10,2) NOT NULL")]
		public decimal COSTO
		{
			get
			{
				return this._COSTO;
			}
			set
			{
				if ((this._COSTO != value))
				{
					this.OnCOSTOChanging(value);
					this.SendPropertyChanging();
					this._COSTO = value;
					this.SendPropertyChanged("COSTO");
					this.OnCOSTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORRADO_E", DbType="Bit NOT NULL")]
		public bool BORRADO_E
		{
			get
			{
				return this._BORRADO_E;
			}
			set
			{
				if ((this._BORRADO_E != value))
				{
					this.OnBORRADO_EChanging(value);
					this.SendPropertyChanging();
					this._BORRADO_E = value;
					this.SendPropertyChanged("BORRADO_E");
					this.OnBORRADO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_CLASES", Storage="_CLASES", ThisKey="ID_CURSO", OtherKey="ID_CURSO")]
		public EntitySet<CLASES> CLASES
		{
			get
			{
				return this._CLASES;
			}
			set
			{
				this._CLASES.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_CURSOS_ESTUDIANTE", Storage="_CURSOS_ESTUDIANTE", ThisKey="ID_CURSO", OtherKey="ID_CURSO")]
		public EntitySet<CURSOS_ESTUDIANTE> CURSOS_ESTUDIANTE
		{
			get
			{
				return this._CURSOS_ESTUDIANTE;
			}
			set
			{
				this._CURSOS_ESTUDIANTE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_MATRICULA", Storage="_MATRICULA", ThisKey="ID_CURSO", OtherKey="ID_CURSO")]
		public EntitySet<MATRICULA> MATRICULA
		{
			get
			{
				return this._MATRICULA;
			}
			set
			{
				this._MATRICULA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROGRAMA_CURSOS", Storage="_PROGRAMA", ThisKey="ID_PROGRAMA", OtherKey="ID_PROGRAMA", IsForeignKey=true)]
		public PROGRAMA PROGRAMA
		{
			get
			{
				return this._PROGRAMA.Entity;
			}
			set
			{
				PROGRAMA previousValue = this._PROGRAMA.Entity;
				if (((previousValue != value) 
							|| (this._PROGRAMA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROGRAMA.Entity = null;
						previousValue.CURSOS1.Remove(this);
					}
					this._PROGRAMA.Entity = value;
					if ((value != null))
					{
						value.CURSOS1.Add(this);
						this._ID_PROGRAMA = value.ID_PROGRAMA;
					}
					else
					{
						this._ID_PROGRAMA = default(int);
					}
					this.SendPropertyChanged("PROGRAMA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLASES(CLASES entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = this;
		}
		
		private void detach_CLASES(CLASES entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = null;
		}
		
		private void attach_CURSOS_ESTUDIANTE(CURSOS_ESTUDIANTE entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = this;
		}
		
		private void detach_CURSOS_ESTUDIANTE(CURSOS_ESTUDIANTE entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = null;
		}
		
		private void attach_MATRICULA(MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = this;
		}
		
		private void detach_MATRICULA(MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CURSOS_ESTUDIANTE")]
	public partial class CURSOS_ESTUDIANTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CURSO;
		
		private int _ID_ESTUDIANTE;
		
		private string _NOMBRE_CURSO;
		
		private System.DateTime _FECHA_INICIO;
		
		private System.DateTime _FECHA_FINAL;
		
		private string _ESTADO;
		
		private int _HORAS_SINC_RES;
		
		private bool _BORRADO_E;
		
		private EntityRef<CURSOS> _CURSOS;
		
		private EntityRef<ESTUDIANTES> _ESTUDIANTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CURSOChanging(int value);
    partial void OnID_CURSOChanged();
    partial void OnID_ESTUDIANTEChanging(int value);
    partial void OnID_ESTUDIANTEChanged();
    partial void OnNOMBRE_CURSOChanging(string value);
    partial void OnNOMBRE_CURSOChanged();
    partial void OnFECHA_INICIOChanging(System.DateTime value);
    partial void OnFECHA_INICIOChanged();
    partial void OnFECHA_FINALChanging(System.DateTime value);
    partial void OnFECHA_FINALChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnHORAS_SINC_RESChanging(int value);
    partial void OnHORAS_SINC_RESChanged();
    partial void OnBORRADO_EChanging(bool value);
    partial void OnBORRADO_EChanged();
    #endregion
		
		public CURSOS_ESTUDIANTE()
		{
			this._CURSOS = default(EntityRef<CURSOS>);
			this._ESTUDIANTES = default(EntityRef<ESTUDIANTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CURSO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CURSO
		{
			get
			{
				return this._ID_CURSO;
			}
			set
			{
				if ((this._ID_CURSO != value))
				{
					if (this._CURSOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CURSOChanging(value);
					this.SendPropertyChanging();
					this._ID_CURSO = value;
					this.SendPropertyChanged("ID_CURSO");
					this.OnID_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTUDIANTE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_ESTUDIANTE
		{
			get
			{
				return this._ID_ESTUDIANTE;
			}
			set
			{
				if ((this._ID_ESTUDIANTE != value))
				{
					if (this._ESTUDIANTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ESTUDIANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_ESTUDIANTE = value;
					this.SendPropertyChanged("ID_ESTUDIANTE");
					this.OnID_ESTUDIANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CURSO", DbType="VarChar(100)")]
		public string NOMBRE_CURSO
		{
			get
			{
				return this._NOMBRE_CURSO;
			}
			set
			{
				if ((this._NOMBRE_CURSO != value))
				{
					this.OnNOMBRE_CURSOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_CURSO = value;
					this.SendPropertyChanged("NOMBRE_CURSO");
					this.OnNOMBRE_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this.OnFECHA_INICIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INICIO = value;
					this.SendPropertyChanged("FECHA_INICIO");
					this.OnFECHA_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_FINAL", DbType="Date NOT NULL")]
		public System.DateTime FECHA_FINAL
		{
			get
			{
				return this._FECHA_FINAL;
			}
			set
			{
				if ((this._FECHA_FINAL != value))
				{
					this.OnFECHA_FINALChanging(value);
					this.SendPropertyChanging();
					this._FECHA_FINAL = value;
					this.SendPropertyChanged("FECHA_FINAL");
					this.OnFECHA_FINALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAS_SINC_RES", DbType="Int NOT NULL")]
		public int HORAS_SINC_RES
		{
			get
			{
				return this._HORAS_SINC_RES;
			}
			set
			{
				if ((this._HORAS_SINC_RES != value))
				{
					this.OnHORAS_SINC_RESChanging(value);
					this.SendPropertyChanging();
					this._HORAS_SINC_RES = value;
					this.SendPropertyChanged("HORAS_SINC_RES");
					this.OnHORAS_SINC_RESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORRADO_E", DbType="Bit NOT NULL")]
		public bool BORRADO_E
		{
			get
			{
				return this._BORRADO_E;
			}
			set
			{
				if ((this._BORRADO_E != value))
				{
					this.OnBORRADO_EChanging(value);
					this.SendPropertyChanging();
					this._BORRADO_E = value;
					this.SendPropertyChanged("BORRADO_E");
					this.OnBORRADO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_CURSOS_ESTUDIANTE", Storage="_CURSOS", ThisKey="ID_CURSO", OtherKey="ID_CURSO", IsForeignKey=true)]
		public CURSOS CURSOS
		{
			get
			{
				return this._CURSOS.Entity;
			}
			set
			{
				CURSOS previousValue = this._CURSOS.Entity;
				if (((previousValue != value) 
							|| (this._CURSOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CURSOS.Entity = null;
						previousValue.CURSOS_ESTUDIANTE.Remove(this);
					}
					this._CURSOS.Entity = value;
					if ((value != null))
					{
						value.CURSOS_ESTUDIANTE.Add(this);
						this._ID_CURSO = value.ID_CURSO;
					}
					else
					{
						this._ID_CURSO = default(int);
					}
					this.SendPropertyChanged("CURSOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_CURSOS_ESTUDIANTE", Storage="_ESTUDIANTES", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE", IsForeignKey=true)]
		public ESTUDIANTES ESTUDIANTES
		{
			get
			{
				return this._ESTUDIANTES.Entity;
			}
			set
			{
				ESTUDIANTES previousValue = this._ESTUDIANTES.Entity;
				if (((previousValue != value) 
							|| (this._ESTUDIANTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ESTUDIANTES.Entity = null;
						previousValue.CURSOS_ESTUDIANTE.Remove(this);
					}
					this._ESTUDIANTES.Entity = value;
					if ((value != null))
					{
						value.CURSOS_ESTUDIANTE.Add(this);
						this._ID_ESTUDIANTE = value.ID_ESTUDIANTE;
					}
					else
					{
						this._ID_ESTUDIANTE = default(int);
					}
					this.SendPropertyChanged("ESTUDIANTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ESTUDIANTES")]
	public partial class ESTUDIANTES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ESTUDIANTE;
		
		private string _NOMBRE;
		
		private string _P_APELLIDO;
		
		private string _S_APELLIDO;
		
		private int _EDAD;
		
		private string _TELEFONO;
		
		private string _EMAIL;
		
		private bool _DEUDA;
		
		private System.Nullable<int> _CURSOS_MATRICULADOS;
		
		private bool _BORRADO_E;
		
		private EntitySet<CLASES> _CLASES;
		
		private EntitySet<CURSOS_ESTUDIANTE> _CURSOS_ESTUDIANTE;
		
		private EntitySet<LOGINS> _LOGINS;
		
		private EntitySet<MATRICULA> _MATRICULA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ESTUDIANTEChanging(int value);
    partial void OnID_ESTUDIANTEChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnP_APELLIDOChanging(string value);
    partial void OnP_APELLIDOChanged();
    partial void OnS_APELLIDOChanging(string value);
    partial void OnS_APELLIDOChanged();
    partial void OnEDADChanging(int value);
    partial void OnEDADChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnDEUDAChanging(bool value);
    partial void OnDEUDAChanged();
    partial void OnCURSOS_MATRICULADOSChanging(System.Nullable<int> value);
    partial void OnCURSOS_MATRICULADOSChanged();
    partial void OnBORRADO_EChanging(bool value);
    partial void OnBORRADO_EChanged();
    #endregion
		
		public ESTUDIANTES()
		{
			this._CLASES = new EntitySet<CLASES>(new Action<CLASES>(this.attach_CLASES), new Action<CLASES>(this.detach_CLASES));
			this._CURSOS_ESTUDIANTE = new EntitySet<CURSOS_ESTUDIANTE>(new Action<CURSOS_ESTUDIANTE>(this.attach_CURSOS_ESTUDIANTE), new Action<CURSOS_ESTUDIANTE>(this.detach_CURSOS_ESTUDIANTE));
			this._LOGINS = new EntitySet<LOGINS>(new Action<LOGINS>(this.attach_LOGINS), new Action<LOGINS>(this.detach_LOGINS));
			this._MATRICULA = new EntitySet<MATRICULA>(new Action<MATRICULA>(this.attach_MATRICULA), new Action<MATRICULA>(this.detach_MATRICULA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTUDIANTE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ESTUDIANTE
		{
			get
			{
				return this._ID_ESTUDIANTE;
			}
			set
			{
				if ((this._ID_ESTUDIANTE != value))
				{
					this.OnID_ESTUDIANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_ESTUDIANTE = value;
					this.SendPropertyChanged("ID_ESTUDIANTE");
					this.OnID_ESTUDIANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_APELLIDO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string P_APELLIDO
		{
			get
			{
				return this._P_APELLIDO;
			}
			set
			{
				if ((this._P_APELLIDO != value))
				{
					this.OnP_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._P_APELLIDO = value;
					this.SendPropertyChanged("P_APELLIDO");
					this.OnP_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_APELLIDO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string S_APELLIDO
		{
			get
			{
				return this._S_APELLIDO;
			}
			set
			{
				if ((this._S_APELLIDO != value))
				{
					this.OnS_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._S_APELLIDO = value;
					this.SendPropertyChanged("S_APELLIDO");
					this.OnS_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDAD", DbType="Int NOT NULL")]
		public int EDAD
		{
			get
			{
				return this._EDAD;
			}
			set
			{
				if ((this._EDAD != value))
				{
					this.OnEDADChanging(value);
					this.SendPropertyChanging();
					this._EDAD = value;
					this.SendPropertyChanged("EDAD");
					this.OnEDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEUDA", DbType="Bit NOT NULL")]
		public bool DEUDA
		{
			get
			{
				return this._DEUDA;
			}
			set
			{
				if ((this._DEUDA != value))
				{
					this.OnDEUDAChanging(value);
					this.SendPropertyChanging();
					this._DEUDA = value;
					this.SendPropertyChanged("DEUDA");
					this.OnDEUDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURSOS_MATRICULADOS", DbType="Int")]
		public System.Nullable<int> CURSOS_MATRICULADOS
		{
			get
			{
				return this._CURSOS_MATRICULADOS;
			}
			set
			{
				if ((this._CURSOS_MATRICULADOS != value))
				{
					this.OnCURSOS_MATRICULADOSChanging(value);
					this.SendPropertyChanging();
					this._CURSOS_MATRICULADOS = value;
					this.SendPropertyChanged("CURSOS_MATRICULADOS");
					this.OnCURSOS_MATRICULADOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORRADO_E", DbType="Bit NOT NULL")]
		public bool BORRADO_E
		{
			get
			{
				return this._BORRADO_E;
			}
			set
			{
				if ((this._BORRADO_E != value))
				{
					this.OnBORRADO_EChanging(value);
					this.SendPropertyChanging();
					this._BORRADO_E = value;
					this.SendPropertyChanged("BORRADO_E");
					this.OnBORRADO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_CLASES", Storage="_CLASES", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE")]
		public EntitySet<CLASES> CLASES
		{
			get
			{
				return this._CLASES;
			}
			set
			{
				this._CLASES.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_CURSOS_ESTUDIANTE", Storage="_CURSOS_ESTUDIANTE", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE")]
		public EntitySet<CURSOS_ESTUDIANTE> CURSOS_ESTUDIANTE
		{
			get
			{
				return this._CURSOS_ESTUDIANTE;
			}
			set
			{
				this._CURSOS_ESTUDIANTE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_LOGINS", Storage="_LOGINS", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE")]
		public EntitySet<LOGINS> LOGINS
		{
			get
			{
				return this._LOGINS;
			}
			set
			{
				this._LOGINS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_MATRICULA", Storage="_MATRICULA", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE")]
		public EntitySet<MATRICULA> MATRICULA
		{
			get
			{
				return this._MATRICULA;
			}
			set
			{
				this._MATRICULA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLASES(CLASES entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = this;
		}
		
		private void detach_CLASES(CLASES entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = null;
		}
		
		private void attach_CURSOS_ESTUDIANTE(CURSOS_ESTUDIANTE entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = this;
		}
		
		private void detach_CURSOS_ESTUDIANTE(CURSOS_ESTUDIANTE entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = null;
		}
		
		private void attach_LOGINS(LOGINS entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = this;
		}
		
		private void detach_LOGINS(LOGINS entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = null;
		}
		
		private void attach_MATRICULA(MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = this;
		}
		
		private void detach_MATRICULA(MATRICULA entity)
		{
			this.SendPropertyChanging();
			entity.ESTUDIANTES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FERIADOS")]
	public partial class FERIADOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _FECHA;
		
		private string _DESCRIPCION;
		
		private int _ANIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFECHAChanging(System.DateTime value);
    partial void OnFECHAChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnANIOChanging(int value);
    partial void OnANIOChanged();
    #endregion
		
		public FERIADOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(100)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANIO", DbType="Int NOT NULL")]
		public int ANIO
		{
			get
			{
				return this._ANIO;
			}
			set
			{
				if ((this._ANIO != value))
				{
					this.OnANIOChanging(value);
					this.SendPropertyChanging();
					this._ANIO = value;
					this.SendPropertyChanged("ANIO");
					this.OnANIOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOGINS")]
	public partial class LOGINS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USUARIO;
		
		private int _ID_ESTUDIANTE;
		
		private string _CONTRASENA;
		
		private EntityRef<ESTUDIANTES> _ESTUDIANTES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSUARIOChanging(string value);
    partial void OnUSUARIOChanged();
    partial void OnID_ESTUDIANTEChanging(int value);
    partial void OnID_ESTUDIANTEChanged();
    partial void OnCONTRASENAChanging(string value);
    partial void OnCONTRASENAChanged();
    #endregion
		
		public LOGINS()
		{
			this._ESTUDIANTES = default(EntityRef<ESTUDIANTES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USUARIO
		{
			get
			{
				return this._USUARIO;
			}
			set
			{
				if ((this._USUARIO != value))
				{
					this.OnUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._USUARIO = value;
					this.SendPropertyChanged("USUARIO");
					this.OnUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTUDIANTE", DbType="Int NOT NULL")]
		public int ID_ESTUDIANTE
		{
			get
			{
				return this._ID_ESTUDIANTE;
			}
			set
			{
				if ((this._ID_ESTUDIANTE != value))
				{
					if (this._ESTUDIANTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ESTUDIANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_ESTUDIANTE = value;
					this.SendPropertyChanged("ID_ESTUDIANTE");
					this.OnID_ESTUDIANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASENA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CONTRASENA
		{
			get
			{
				return this._CONTRASENA;
			}
			set
			{
				if ((this._CONTRASENA != value))
				{
					this.OnCONTRASENAChanging(value);
					this.SendPropertyChanging();
					this._CONTRASENA = value;
					this.SendPropertyChanged("CONTRASENA");
					this.OnCONTRASENAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_LOGINS", Storage="_ESTUDIANTES", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE", IsForeignKey=true)]
		public ESTUDIANTES ESTUDIANTES
		{
			get
			{
				return this._ESTUDIANTES.Entity;
			}
			set
			{
				ESTUDIANTES previousValue = this._ESTUDIANTES.Entity;
				if (((previousValue != value) 
							|| (this._ESTUDIANTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ESTUDIANTES.Entity = null;
						previousValue.LOGINS.Remove(this);
					}
					this._ESTUDIANTES.Entity = value;
					if ((value != null))
					{
						value.LOGINS.Add(this);
						this._ID_ESTUDIANTE = value.ID_ESTUDIANTE;
					}
					else
					{
						this._ID_ESTUDIANTE = default(int);
					}
					this.SendPropertyChanged("ESTUDIANTES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATRICULA")]
	public partial class MATRICULA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MATRICULA;
		
		private int _ID_ESTUDIANTE;
		
		private int _ID_CURSO;
		
		private string _IDIOMA;
		
		private System.DateTime _FECHA;
		
		private string _NIVEL_INTENSIDAD;
		
		private decimal _COSTO;
		
		private bool _CANCELADO;
		
		private bool _BORRADO_E;
		
		private EntityRef<ESTUDIANTES> _ESTUDIANTES;
		
		private EntityRef<CURSOS> _CURSOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MATRICULAChanging(int value);
    partial void OnID_MATRICULAChanged();
    partial void OnID_ESTUDIANTEChanging(int value);
    partial void OnID_ESTUDIANTEChanged();
    partial void OnID_CURSOChanging(int value);
    partial void OnID_CURSOChanged();
    partial void OnIDIOMAChanging(string value);
    partial void OnIDIOMAChanged();
    partial void OnFECHAChanging(System.DateTime value);
    partial void OnFECHAChanged();
    partial void OnNIVEL_INTENSIDADChanging(string value);
    partial void OnNIVEL_INTENSIDADChanged();
    partial void OnCOSTOChanging(decimal value);
    partial void OnCOSTOChanged();
    partial void OnCANCELADOChanging(bool value);
    partial void OnCANCELADOChanged();
    partial void OnBORRADO_EChanging(bool value);
    partial void OnBORRADO_EChanged();
    #endregion
		
		public MATRICULA()
		{
			this._ESTUDIANTES = default(EntityRef<ESTUDIANTES>);
			this._CURSOS = default(EntityRef<CURSOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MATRICULA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_MATRICULA
		{
			get
			{
				return this._ID_MATRICULA;
			}
			set
			{
				if ((this._ID_MATRICULA != value))
				{
					this.OnID_MATRICULAChanging(value);
					this.SendPropertyChanging();
					this._ID_MATRICULA = value;
					this.SendPropertyChanged("ID_MATRICULA");
					this.OnID_MATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ESTUDIANTE", DbType="Int NOT NULL")]
		public int ID_ESTUDIANTE
		{
			get
			{
				return this._ID_ESTUDIANTE;
			}
			set
			{
				if ((this._ID_ESTUDIANTE != value))
				{
					if (this._ESTUDIANTES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ESTUDIANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_ESTUDIANTE = value;
					this.SendPropertyChanged("ID_ESTUDIANTE");
					this.OnID_ESTUDIANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CURSO", DbType="Int NOT NULL")]
		public int ID_CURSO
		{
			get
			{
				return this._ID_CURSO;
			}
			set
			{
				if ((this._ID_CURSO != value))
				{
					if (this._CURSOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CURSOChanging(value);
					this.SendPropertyChanging();
					this._ID_CURSO = value;
					this.SendPropertyChanged("ID_CURSO");
					this.OnID_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDIOMA", DbType="VarChar(20)")]
		public string IDIOMA
		{
			get
			{
				return this._IDIOMA;
			}
			set
			{
				if ((this._IDIOMA != value))
				{
					this.OnIDIOMAChanging(value);
					this.SendPropertyChanging();
					this._IDIOMA = value;
					this.SendPropertyChanged("IDIOMA");
					this.OnIDIOMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA", DbType="Date NOT NULL")]
		public System.DateTime FECHA
		{
			get
			{
				return this._FECHA;
			}
			set
			{
				if ((this._FECHA != value))
				{
					this.OnFECHAChanging(value);
					this.SendPropertyChanging();
					this._FECHA = value;
					this.SendPropertyChanged("FECHA");
					this.OnFECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL_INTENSIDAD", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NIVEL_INTENSIDAD
		{
			get
			{
				return this._NIVEL_INTENSIDAD;
			}
			set
			{
				if ((this._NIVEL_INTENSIDAD != value))
				{
					this.OnNIVEL_INTENSIDADChanging(value);
					this.SendPropertyChanging();
					this._NIVEL_INTENSIDAD = value;
					this.SendPropertyChanged("NIVEL_INTENSIDAD");
					this.OnNIVEL_INTENSIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTO", DbType="Decimal(10,2) NOT NULL")]
		public decimal COSTO
		{
			get
			{
				return this._COSTO;
			}
			set
			{
				if ((this._COSTO != value))
				{
					this.OnCOSTOChanging(value);
					this.SendPropertyChanging();
					this._COSTO = value;
					this.SendPropertyChanged("COSTO");
					this.OnCOSTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCELADO", DbType="Bit NOT NULL")]
		public bool CANCELADO
		{
			get
			{
				return this._CANCELADO;
			}
			set
			{
				if ((this._CANCELADO != value))
				{
					this.OnCANCELADOChanging(value);
					this.SendPropertyChanging();
					this._CANCELADO = value;
					this.SendPropertyChanged("CANCELADO");
					this.OnCANCELADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORRADO_E", DbType="Bit NOT NULL")]
		public bool BORRADO_E
		{
			get
			{
				return this._BORRADO_E;
			}
			set
			{
				if ((this._BORRADO_E != value))
				{
					this.OnBORRADO_EChanging(value);
					this.SendPropertyChanging();
					this._BORRADO_E = value;
					this.SendPropertyChanged("BORRADO_E");
					this.OnBORRADO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ESTUDIANTES_MATRICULA", Storage="_ESTUDIANTES", ThisKey="ID_ESTUDIANTE", OtherKey="ID_ESTUDIANTE", IsForeignKey=true)]
		public ESTUDIANTES ESTUDIANTES
		{
			get
			{
				return this._ESTUDIANTES.Entity;
			}
			set
			{
				ESTUDIANTES previousValue = this._ESTUDIANTES.Entity;
				if (((previousValue != value) 
							|| (this._ESTUDIANTES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ESTUDIANTES.Entity = null;
						previousValue.MATRICULA.Remove(this);
					}
					this._ESTUDIANTES.Entity = value;
					if ((value != null))
					{
						value.MATRICULA.Add(this);
						this._ID_ESTUDIANTE = value.ID_ESTUDIANTE;
					}
					else
					{
						this._ID_ESTUDIANTE = default(int);
					}
					this.SendPropertyChanged("ESTUDIANTES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_MATRICULA", Storage="_CURSOS", ThisKey="ID_CURSO", OtherKey="ID_CURSO", IsForeignKey=true)]
		public CURSOS CURSOS
		{
			get
			{
				return this._CURSOS.Entity;
			}
			set
			{
				CURSOS previousValue = this._CURSOS.Entity;
				if (((previousValue != value) 
							|| (this._CURSOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CURSOS.Entity = null;
						previousValue.MATRICULA.Remove(this);
					}
					this._CURSOS.Entity = value;
					if ((value != null))
					{
						value.MATRICULA.Add(this);
						this._ID_CURSO = value.ID_CURSO;
					}
					else
					{
						this._ID_CURSO = default(int);
					}
					this.SendPropertyChanged("CURSOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROFESORES")]
	public partial class PROFESORES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PROFESOR;
		
		private string _NOMBRE;
		
		private string _P_APELLIDO;
		
		private string _S_APELLIDO;
		
		private int _EDAD;
		
		private string _TELEFONO;
		
		private string _EMAIL;
		
		private string _IDIOMA;
		
		private System.Nullable<System.TimeSpan> _HORA_ENTRADA;
		
		private System.Nullable<System.TimeSpan> _HORA_SALIDA;
		
		private bool _BORRADO_E;
		
		private EntitySet<CLASES> _CLASES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PROFESORChanging(int value);
    partial void OnID_PROFESORChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnP_APELLIDOChanging(string value);
    partial void OnP_APELLIDOChanged();
    partial void OnS_APELLIDOChanging(string value);
    partial void OnS_APELLIDOChanged();
    partial void OnEDADChanging(int value);
    partial void OnEDADChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnIDIOMAChanging(string value);
    partial void OnIDIOMAChanged();
    partial void OnHORA_ENTRADAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORA_ENTRADAChanged();
    partial void OnHORA_SALIDAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORA_SALIDAChanged();
    partial void OnBORRADO_EChanging(bool value);
    partial void OnBORRADO_EChanged();
    #endregion
		
		public PROFESORES()
		{
			this._CLASES = new EntitySet<CLASES>(new Action<CLASES>(this.attach_CLASES), new Action<CLASES>(this.detach_CLASES));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFESOR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PROFESOR
		{
			get
			{
				return this._ID_PROFESOR;
			}
			set
			{
				if ((this._ID_PROFESOR != value))
				{
					this.OnID_PROFESORChanging(value);
					this.SendPropertyChanging();
					this._ID_PROFESOR = value;
					this.SendPropertyChanged("ID_PROFESOR");
					this.OnID_PROFESORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_APELLIDO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string P_APELLIDO
		{
			get
			{
				return this._P_APELLIDO;
			}
			set
			{
				if ((this._P_APELLIDO != value))
				{
					this.OnP_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._P_APELLIDO = value;
					this.SendPropertyChanged("P_APELLIDO");
					this.OnP_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_APELLIDO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string S_APELLIDO
		{
			get
			{
				return this._S_APELLIDO;
			}
			set
			{
				if ((this._S_APELLIDO != value))
				{
					this.OnS_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._S_APELLIDO = value;
					this.SendPropertyChanged("S_APELLIDO");
					this.OnS_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDAD", DbType="Int NOT NULL")]
		public int EDAD
		{
			get
			{
				return this._EDAD;
			}
			set
			{
				if ((this._EDAD != value))
				{
					this.OnEDADChanging(value);
					this.SendPropertyChanging();
					this._EDAD = value;
					this.SendPropertyChanged("EDAD");
					this.OnEDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDIOMA", DbType="VarChar(20)")]
		public string IDIOMA
		{
			get
			{
				return this._IDIOMA;
			}
			set
			{
				if ((this._IDIOMA != value))
				{
					this.OnIDIOMAChanging(value);
					this.SendPropertyChanging();
					this._IDIOMA = value;
					this.SendPropertyChanged("IDIOMA");
					this.OnIDIOMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_ENTRADA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_ENTRADA
		{
			get
			{
				return this._HORA_ENTRADA;
			}
			set
			{
				if ((this._HORA_ENTRADA != value))
				{
					this.OnHORA_ENTRADAChanging(value);
					this.SendPropertyChanging();
					this._HORA_ENTRADA = value;
					this.SendPropertyChanged("HORA_ENTRADA");
					this.OnHORA_ENTRADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA_SALIDA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA_SALIDA
		{
			get
			{
				return this._HORA_SALIDA;
			}
			set
			{
				if ((this._HORA_SALIDA != value))
				{
					this.OnHORA_SALIDAChanging(value);
					this.SendPropertyChanging();
					this._HORA_SALIDA = value;
					this.SendPropertyChanged("HORA_SALIDA");
					this.OnHORA_SALIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORRADO_E", DbType="Bit NOT NULL")]
		public bool BORRADO_E
		{
			get
			{
				return this._BORRADO_E;
			}
			set
			{
				if ((this._BORRADO_E != value))
				{
					this.OnBORRADO_EChanging(value);
					this.SendPropertyChanging();
					this._BORRADO_E = value;
					this.SendPropertyChanged("BORRADO_E");
					this.OnBORRADO_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_CLASES", Storage="_CLASES", ThisKey="ID_PROFESOR", OtherKey="ID_PROFESOR")]
		public EntitySet<CLASES> CLASES
		{
			get
			{
				return this._CLASES;
			}
			set
			{
				this._CLASES.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLASES(CLASES entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = this;
		}
		
		private void detach_CLASES(CLASES entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = null;
		}
	}
}
#pragma warning restore 1591
